feat(92): watcher leaving a room, no room deletion
LesGars/WatchWithMe pull request #186
Opened 2020-06-06 10:02 UTC by mourtisma

- Added the leaving the room feature, with a room containing 2 or more watchers
- Moved `findAndEnsureRoomJoined` to `room-operations`

TODO:
- Delete the room if there's no more watcher
- Add more tests

2020-06-06 10:51 UTC, MollardMichael requested changes

2020-06-06 10:51 UTC, MollardMichael commented on backend/functions/disconnect.ts
> +    const { roomId } = disconnectEvent;
How come the room if it's present here? Shouldn't we get at best the connection I'd ?

2020-06-20 12:14 UTC, Startouf approved these changes

2020-07-04 11:57 UTC, Startouf requested changes

2020-07-04 11:57 UTC, Startouf commented on backend/libs/room-operations.ts
> +            '[WS-S] A media event was received for someone ho has not joined the room. Dropping',
```suggestion
            '[WS-S] A media event was received from someone who has not joined the room. Dropping',
```

2020-07-04 11:57 UTC, Startouf commented on backend/libs/room-operations.ts
> +    return updateRoom(room, tableName, dynamoDb);
Non pour le coup pas possible d'utiliser updateRoom pour retirer un watcher. Il nous faut obligatoirement une commande AWS DynamoDB qui supprime la clé + le sous-doc uniquement, et pas une fonction qui mette à jour toute la liste des watchers.

SInon, ça va péter car on aura des pb de race condition avec les autres watchers. Le pb c'est que updateRoom

2026-03-12 00:42 UTC, closed without merging